# monitor(s)
# xrandr --output HDMI-1 --mode 1920x1080 --rate 165.00 --set "vrr_capable" 1 --primary
# xrandr --output eDP-1 --off
# xset s off

# keyboard
# setxkbmap us

# mouse
# xinput --set-prop "Name" "libinput Scrolling Pixel Distance" 10

# disabling CAPS lock
# setxkbmap -option caps:none

# swapping ESC with CAPS lock
# setxkbmap -option caps:swapescape

# audio
# pulseaudio &

# wallpaper
# xwallpaper --center ~/pictures/wallpaper.jpg

# wm
sxhkd &
exec dbus-run-session dk
