# monitor(s)
# xrandr --output HDMI-A-0 -s 1920x1080 -r 144 --primary --set TearFree on
# xset s off

# keyboard layout and mouse sensitivity
# setxkbmap us
# xinput --set-prop "Name" "libinput Scrolling Pixel Distance" 10

# disabling CAPS lock
# setxkbmap -option caps:none

# swapping ESC with CAPS lock
# setxkbmap -option caps:swapescape

# audio
pulseaudio &

# startup
alacritty &
codium &
thorium &
zathura &

# wm
sxhkd &
exec dbus-run-session dk
