#!/bin/sh

# loading sxhkd
pgrep sxhkd || sxhkd -c "$HOME/.config/dk/sxhkdrc" &

logfile="$HOME/.dklog"
{ # compound command to redirect all output

	# number of workspaces
    dkcmd set numws=8
			
	# defaulting to the tile layout
	dkcmd set ws=_ apply layout=tile master=1 stack=3 gap=0 msplit=0.6 ssplit=0.4

	# workspaces names
	dkcmd set \
		ws=1 name="routione" \
		ws=2 name="alacritty" \
		ws=3 name="browser" \
		ws=4 name="code" \
		ws=5 name="read" \
		ws=6 name="play"

	# minimum width/height for resizing and minimum allowed on-screen when moving
	dkcmd set win_minwh=50 win_minxy=10
    
	# no gaps and borders in single window layouts
	dkcmd set smart_gap=true smart_border=true
    
	# obeying hints on windows that draw their own
	dkcmd set obey_motif=true

	# borders
	dkcmd set border width=4 outer_width=0 colour \
		focus='#4ad66d' \
		unfocus='#ffffff' \
		urgent='#ee5555' \
		outer_focus='#4ad66d' \
		outer_unfocus='#ffffff' \
		outer_urgent='#222222'

	# focus on mouse enter
	dkcmd focus_mouse=true

	# mouse
	dkcmd set mouse mod=super move=button3 resize=button1
	
	# disable mouse
	# dkcmd set mouse mod=super move=buttonx resize=buttonx

	# apply current rules
	dkcmd rule apply '*'

} >> "$logfile" 2>&1