#!/bin/sh

# loading sxhkd
pgrep sxhkd || sxhkd -c "$HOME/.config/dk/sxhkdrc" &

logfile="$HOME/.dklog"
{ # compound command to redirect all output

	# number of workspaces
  dkcmd set numws=5

	# defaulting to the tile layout
	dkcmd set ws=_ apply layout=tile master=1 stack=3 gap=0 msplit=0.6 ssplit=0.4

	# workspaces names
	dkcmd set \
		ws=1 name="terminal" \
		ws=2 name="browser" \
		ws=3 name="record" \
		ws=4 name="main" \
		ws=5 name="empty"

	# minimum width/height for resizing and minimum allowed on-screen when moving
	dkcmd set win_minwh=50 win_minxy=10

	# gaps and borders are completely on or off for every window
	dkcmd set smart_gap=false smart_border=false

	# obeying hints on windows that draw their own
	dkcmd set obey_motif=true

	# borders
	dkcmd set border width=0 outer_width=0 colour \
		focus='#4ad66d' \
		unfocus='#ffffff' \
		outer_focus='#4ad66d' \
		outer_unfocus='#ffffff' \

	# mouse
	dkcmd set mouse mod=super move=button1 resize=button3

	# focus on mouse enter
	dkcmd focus_mouse=true

	# rules
	dkcmd rule class="^alacritty$" ws=1 focus=true terminal=true
	dkcmd rule class="^qutebrowser$" ws=2 focus=true
	dkcmd rule class="^obs$" ws=3 focus=false
	dkcmd rule class="^code$" ws=4 focus=false

	# apply current rules
	dkcmd rule apply '*'

} >> "$logfile" 2>&1

# Startup
alacritty &
qutebrowser &
obs &
code &
